### ISSUE TITLE
Favorite Station Issue

### ISSUE THREAD

**Issue by RMutton** [jonthornton/WTFT#1]
If I add the Dykman Street 1 stop to my favorites it resets to the default favorites.

Confirmed on:
Google Chrome mobile, on a Pixel 6 Pro running Android 12. Persisted thru a device reset, a new device, and happens in incognito mode.
Microsoft Edge on Windows 10.
Google Chrome on Windows 10.

**Comment by jonthornton** [comment]
This is fixed by f054e1d, which is now live on wheresthefuckingtrain.com. Thanks for reporting the problem!
